/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as ProjectsRouteImport } from "./routes/projects"
import { Route as ContactRouteImport } from "./routes/contact"
import { Route as AboutRouteImport } from "./routes/about"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as PostsIndexRouteImport } from "./routes/posts/index"
import { Route as PostsSlugRouteImport } from "./routes/posts/$slug"

const ProjectsRoute = ProjectsRouteImport.update({
  id: "/projects",
  path: "/projects",
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: "/contact",
  path: "/contact",
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: "/posts/",
  path: "/posts/",
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: "/posts/$slug",
  path: "/posts/$slug",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/contact": typeof ContactRoute
  "/projects": typeof ProjectsRoute
  "/posts/$slug": typeof PostsSlugRoute
  "/posts": typeof PostsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/contact": typeof ContactRoute
  "/projects": typeof ProjectsRoute
  "/posts/$slug": typeof PostsSlugRoute
  "/posts": typeof PostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/contact": typeof ContactRoute
  "/projects": typeof ProjectsRoute
  "/posts/$slug": typeof PostsSlugRoute
  "/posts/": typeof PostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/about"
    | "/contact"
    | "/projects"
    | "/posts/$slug"
    | "/posts"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/about" | "/contact" | "/projects" | "/posts/$slug" | "/posts"
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/contact"
    | "/projects"
    | "/posts/$slug"
    | "/posts/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRoute
  PostsSlugRoute: typeof PostsSlugRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/projects": {
      id: "/projects"
      path: "/projects"
      fullPath: "/projects"
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/contact": {
      id: "/contact"
      path: "/contact"
      fullPath: "/contact"
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/about": {
      id: "/about"
      path: "/about"
      fullPath: "/about"
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/posts/": {
      id: "/posts/"
      path: "/posts"
      fullPath: "/posts"
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/posts/$slug": {
      id: "/posts/$slug"
      path: "/posts/$slug"
      fullPath: "/posts/$slug"
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRoute,
  PostsSlugRoute: PostsSlugRoute,
  PostsIndexRoute: PostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
